#!/usr/bin/env ruby
require 'subgit'
require 'optparse'

options = {}

OptionParser.new do |opts|
  opts.banner = 'Usage: subgit [operation] [options]'

  opts.on('-h', '--help', 'Mostrar ajuda.') do
    options[:ajuda] = true
  end

  opts.on('-c', '--color-output', 'Mostrar mensagens com cor.') do |c|
    options[:should_color_output] = c
  end

  # opts.on("-u", "--update", "Atualizar o \"spec\".") do |v|
  #   options[:command] = "update"
  # end

  opts.on(
    '-d', \
    '--directory [DIR]', \
    'Diretório onde os comandos devem ser executados.'
  ) do |dir|
    options[:dir] = dir
  end

  opts.on('-f', '--file [FILE]', "Arquivo de 'spec' a ser utilizado.") do |f|
    options[:spec_file] = f
  end
end.parse!

# Guarda a operacao que deve ser utilizada.
operation = ARGV[0]

# Faz a leitura o arquivo passado para ele
# if options[:dir].nil? then
#   raise OptionParser::MissingArgument,"Parâmetro 'file' (-f) não informado."
# end
file = ARGV[1]

# Le o current working directory
# TODO Esse cara precisa ser passado para o sincronizador
pwd = ARGV[2]

# EXTERNALS_ROOT_DIR = "~/svn/cooperalfa/Desenv-1.0.3"
# puts "Utilizando subgit versao: #{Subgit::VERSION}"
puts "Opcoes utilizadas: #{options}"
puts "Utilizando arquivo de spec: [#{file}]"

case operation
when 'externals'
  spec = SpecCreator.new pwd
  spec.print_formatted
when 'sync'
  instance = Subgit::Subgit.new file
  instance.read_and_run
else
  puts "Nenhuma opção selecionada [externals, sync]. Ex: 'subgit sync'"
end
